# Generated by Django 4.2.13 on 2024-11-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0014_remove_reviews_name_reviews_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("like_new", "Like New"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("needs_repair", "Needs Repair"),
                ],
                default="good",
                help_text="Condition of the product being traded in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="eco_friendly_certification",
            field=models.FileField(
                blank=True,
                help_text="Upload eco-friendly certification if applicable",
                null=True,
                upload_to="certifications/",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="estimated_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated trade-in value",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reason_for_trade_in",
            field=models.TextField(
                blank=True, help_text="Reason for trading in the product", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="trade_in_preference",
            field=models.CharField(
                choices=[
                    ("recycle", "Recycle"),
                    ("resell", "Resell"),
                    ("donate", "Donate"),
                ],
                default="recycle",
                help_text="User preference for trade-in (recycle, resell, or donate)",
                max_length=20,
            ),
        ),
    ]
