# Generated by Django 4.2 on 2024-11-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0016_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Mark this product as verified to display on homepage",
            ),
        ),
    ]
